---
label: Project
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: current_work
  type: boolean
  label: Current Work
  description: This is a project you are working on at the moment
- name: categories
  type: field_group
  config: {}
  fields:
  - name: performance
    type: boolean
    label: Performance
    default: true
  - name: design
    type: boolean
    label: Design
  - name: theatre_making
    type: boolean
    label: Theatre Making
  label: Categories
- name: date
  type: datetime
  label: Date
  description: ''
  config:
    required: true
    date_format: DD/MM/YYYY
    time_format: 
    display_utc: false
  default: now
- name: video
  type: boolean
  label: Video
- name: videoLink
  type: text
  config:
    required: false
  label: Video-link
  description: insert the link of the video (from Vimeo Youtube or similar)
  showOnly:
    field: video
    value: true
- name: gallery
  type: image_gallery
  config: {}
  label: Gallery
pages:
- content/projects/150.md
- content/projects/adine-avion.md
- content/projects/aerial-hoop-dance-explorations.md
- content/projects/ar-waith-ar-daith.md
- content/projects/bodies-in-urban-spaces-willi-dorner-1.md
- content/projects/classic-campers-the-classic-way-to-travel-new-zealand.md
- content/projects/homo-irrationalis.md
- content/projects/kitsch-sync-collaborations.md
- content/projects/lispa-gallery.md
- content/projects/maite.md
- content/projects/margaret-and-the-tapeworm.md
- content/projects/maudie-s-rooms.md
- content/projects/mission-control.md
- content/projects/nofit-state-circus-immortal-bianco-tabu.md
- content/projects/persephone-dancing-with-the-shadows.md
- content/projects/profundis.md
- content/projects/repeat-2.md
- content/projects/ruckus-kitsch-sync.md
- content/projects/sacre.md
- content/projects/second-skin.md
- content/projects/shadows-of-a-quiet-society.md
- content/projects/siamber-wen-human-beast-and-solarference.md
- content/projects/silence-echos.md
- content/projects/somewhere-maybe-here.md
- content/projects/souvenirs-of-a-killing.md
- content/projects/tabu-nofitstate-circus.md
- content/projects/the-audition.md
- content/projects/the-colliers-son.md
- content/projects/tokyo-space-dance-butoh-project.md
- content/projects/tundra.md
- content/projects/volver-a-la-vida-tina-pasotra-kusa.md
- content/projects/walk-about-characters.md
- content/projects/you-me-human-tree.md
