---
label: Project
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: categories
  type: field_group
  config: {}
  fields:
  - name: performance
    type: boolean
    label: Performance
    default: true
  - name: design
    type: boolean
    label: Design
  - name: theatre_making
    type: boolean
    label: Theatre Making
  label: Categories
- name: date
  type: datetime
  label: Date
  description: ''
  config:
    required: true
    date_format: DD/MM/YYYY
    time_format: 
    display_utc: false
  default: now
- name: video
  type: boolean
  label: Video
- name: videoLink
  type: text
  config:
    required: false
  label: Video-link
  description: insert the link of the video (from Vimeo Youtube or similar)
  showOnly:
    field: video
    value: true
- name: gallery
  type: image_gallery
  config: {}
  label: Gallery
pages:
- content/projects/mission-control.md
